In [1]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [5]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [24]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[1])

first row: [4 5 6]


In [26]:
print("slicing row:",a1[:2])

slicing row: [[1 2 3]
 [4 5 6]]


In [31]:
print("slicing column:",a1[0:])

slicing column: [[1 2 3]
 [4 5 6]]


In [32]:
print("row and column:",a1[1:1])

row and column: []


In [45]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value:",np.min(a1))
print("max value:",np.max(a1))
print("mean value:",np.mean(a1))
print("median value:",np.median(a1))

[3.18845312 5.06046291 5.55691775 4.27513038 4.09977225 6.50173833
 4.39887541 5.34057754 4.30930576 3.04121773]
min value: 3.0412177318827895
max value: 6.501738325389826
mean value: 4.577245118916732
median value: 4.354090588934817
